name: Some Cache

on:
  push:
    paths:
      - '.github/workflows/cache.yml'
  repository_dispatch:
    types:
      - cache*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cache Restore-only Test
      uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      with:
        path: dummy
        key: ${{ runner.os }}-dummy
      if: "contains(github.event.action, 'restore')"

    - name: Cache Test
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      with:
        path: dummy
        key: ${{ runner.os }}-dummy
      if: "!contains(github.event.action, 'restore')"

    - name: Check dummy
      run: |
        ls -alR dummy || :

    - name: Generate Dummy Data
      run: mkdir -pv dummy && echo data > dummy/data.txt

    - name: Use Dummy Data
      run: cat dummy/data.txt
