name: Some Cache

on:
  push:
    paths:
      - '.github/workflows/cache.yml'
  repository_dispatch:
    types:
      - cache*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check restore only
      id: restore_only
      run: |
        echo action_suffix="/restore" >> $GITHUB_OUTPUT
      if: contains(github.event.action, 'restore')

    - name: Cache Test
      id: cache-tests
      uses: actions/cache${{ steps.restore_only.outputs.action_suffix }}@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: dummy
        key: ${{ runner.os }}-dummy

    - name: Check dummy
      run: |
        ls -alR dummy || :

    - name: Generate Dummy Data
      run: mkdir -pv dummy && echo data > dummy/data.txt

    - name: Use Dummy Data
      run: cat dummy/data.txt
