name: CI

#on: [push]
on: check_run

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download current index.html
      run: |
        curl -o /tmp/index.html https://rubyci.s3.amazonaws.com/doxygen-latest-html/index.html || touch /tmp/index.html
        grep projectnumber /tmp/index.html || :
        echo "GITHUB_SHA=${GITHUB_SHA}"
        if grep -q "${GITHUB_SHA}" /tmp/index.html; then
          echo "##[set-env name=SKIP]doxygen"
        fi
        echo "##[set-env name=SOME_VAR]some text"
    - name: ls /tmp
      run: |
        ls -al /tmp
    - name: env
      run: |
        env | sort
