name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download current index.html
      run: |
        mkdir -p tmp
        curl -o tmp/index.html https://rubyci.s3.amazonaws.com/doxygen-latest-html/index.html || touch tmp/index.html
    - name: Skip if match
      run: |
        grep -q 4209066f0e2be775357d09cb513c89a2f064a335 tmp/index.html && exit
        echo match
    - name: Skip if not match
      run: |
        grep -q 4209066f0e2be775357d09cb513c89a2f064a335 tmp/index.html || exit
        echo not match
