name: ruby-cygwin
on:
  push:
    branches:
      - master

jobs:
  make:
    strategy:
      matrix:
        test_task: [test]
        os: [windows-2019]
        vs: [2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    steps:
      - uses: actions/cache@v1
        with:
          path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
          key: ${{ runner.os }}-cygwin-chocolatey-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cygwin-chocolatey-${{ matrix.os }}-
            ${{ runner.os }}-cygwin-chocolatey-
      - name: Install cygwin base packages with chocolatey
        run: |
          choco install --no-progress cygwin
      - name: Install cygwin additional packages
        run: |
          C:\tools\cygwin\cygwinsetup.exe -qgnNdO -P zlib-devel
        shell: cmd
