name: Docs

on:
  schedule:
    - cron: '15 0 * * *'
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  make:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - ref: "ruby_3_3"
            version: "3.3"
          - ref: "master"
            version: "master"

    steps:
      - uses: actions/checkout@b32f140b0c872d58512e0a66172253c302617b90
        with:
          repository: "ruby/ruby"
          ref: "${{ matrix.ref }}"
          path: "sources/${{ matrix.version }}"

      - name: Make
        run: |
          set -euxo pipefail
          cd sources/${{ matrix.version }}
          ./autogen.sh || autoconf
          ./configure --disable-install-doc
          make -j2

      - name: Make HTML
        run: >-
          make html
          -C "sources/${{ matrix.version }}"
          RDOCOPTS="--title=\"Documentation for Ruby ${{ matrix.version }}\" --main=README.md"
          HTMLOUT="/tmp/html/en/${{ matrix.version }}"

      - name: Make archive
        run: >-
          env XZ_OPT=-9e
          tar -C /tmp/html/en --owner=root --group=root -acvf /tmp/ruby-docs-en-${{ matrix.version }}.tar.xz ${{ matrix.version }}
          HTMLOUT="/tmp/html/en/${{ matrix.version }}"

      - uses: actions/upload-artifact@ef09cdac3e2d3e60d8ccadda691f4f1cec5035cb
        with:
          name: "en-${{ matrix.ref }}"
          retention-days: 3
          path: "/tmp/ruby-docs-en-${{ matrix.version }}.tar.xz"
