name: dump

on:
  schedule:
    - cron: '5 0 * * *'
  push:
    branches:
      - '*'
    tags:
      - '*'
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          echo "action_state=yellow" >> $GITHUB_ENV
          echo "action_fruit=strawberry" >> $GITHUB_OUTPUT
          echo "::debug file=app.js,line=1::Entered octocatAddition method"
          echo "::warning file=app.js,line=1,col=5::Missing semicolon"
          echo "::error file=app.js,line=10,col=15::Something went wrong"
          echo "::add-mask::Mona The Octocat"
          MY_NAME="Mona The Octocat"
          echo "::add-mask::$MY_NAME"
          stopMarker=$(uuidgen)
          echo "::stop-commands::$stopMarker"
          echo dummy
          echo "::$stopMarker::"
      - run: env | sort
      - run: |
          ulimit -a
          ulimit -c unlimited
          ulimit -a
      - run: ulimit -a
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - run: ls -lR $GITHUB_WORKSPACE
        if: false
      - run: |
          if [ -d /github/home -a ! -e /home/runner ]; then
            ln -s /github/home /home/runner
          fi
      - run: |
          set -x
          ls -al "$HOME/.config"
          chmod -v a-w $HOME $HOME/.config
          ls -al "$HOME/.config"
      - uses: ruby/action-slack@0bd85c72233cdbb6a0fe01d37aaeff1d21b5fce1 # v3.2.1
        with:
          payload: |
            {
              "attachments": [{
                "text": "${{ job.status }}: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}> "
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#      - uses: ./.github/actions/notify-slack
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: 8398a7/action-slack@v3
        with:
          author_name: "${{ github.workflow }}"
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,job,took,eventName,ref,workflow,workflowRun,pullRequest
          # channel: "#random"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
