on: push

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Set env
        run: |
          echo '##[set-env name=JOBS]'-j$((1 + $(nproc --all)))
          echo '##[set-env name=SKIP_DOXYGEN]'true
      - name: Show env
        run: env | sort
      - name: skip test 'true'
        run: echo test
        if: job.env.SKIP_DOXYGEN == 'true'
      - name: skip test true
        run: echo test
        if: job.env.SKIP_DOXYGEN == true
      - name: test not set
        run: echo not set
        if: job.env.FOO_BAR == 'not set'

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
