name: example

on:
  push:
    paths:
      - '.github/workflows/example.yml'
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        matrix_var: [3.0]
      fail-fast: false
    steps:
      - name: env 3.0
        env:
          env_var: 3.0
        run: |
          set -x
          echo ${env_var}
          echo ${{matrix_var}}
