name: ruby-macos
on:
  repository_dispatch:
    types:
      - ruby-macos

jobs:
  latest:
    runs-on: macos-latest
    strategy:
      matrix:
        test_task: [ "check", "test-bundler", "test-bundled-gems" ]
      fail-fast: false
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Disable Firewall
        run: |
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate
      # Not using official actions/checkout because it's unstable and sometimes doesn't work for a fork.
      - name: Checkout ruby/ruby
        run: |
          git clone --depth=50 https://github.com/ruby/ruby src
      - name: Install libraries
        run: |
          export WAITS='5 60'
          cd src
          tool/travis_retry.sh brew update
          tool/travis_retry.sh brew install gdbm gmp libffi openssl@1.1 zlib autoconf automake libtool readline
      - name: Set ENV
        run: |
          echo '##[set-env name=JOBS]'-j$((1 + $(sysctl -n hw.activecpu)))
      - name: Autoconf
        run: |
          cd src
          autoconf
      - name: Configure
        run: |
          mkdir build
          cd build
          ../src/configure -C --disable-install-doc --with-openssl-dir=$(brew --prefix openssl@1.1) --with-readline-dir=$(brew --prefix readline)
      - name: Make
        run: make -C build $JOBS
      - name: Tests
        run: make -C build $JOBS -s ${{ matrix.test_task }}
        env:
          MSPECOPT: "-ff" # not using `-j` because sometimes `mspec -j` silently dies
          RUBY_TESTOPTS: "-q --tty=no"
          # Remove minitest from TEST_BUNDLED_GEMS_ALLOW_FAILURES if https://github.com/seattlerb/minitest/pull/798 is resolved
          TEST_BUNDLED_GEMS_ALLOW_FAILURES: "minitest"
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v1
        if: always()
