name: repository_dispatch

on:
  repository_dispatch:
    types:
      - foo
      - bar
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2016, windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "::set-env name=COMMIT_TIMESTAMP::$(git log -1 --format=%ct)"
          LOGS=$(TZ=UTC git log --since='0:00' --date=iso-local --format=%cd)
          echo "$LOGS"
          COUNT=$(echo "$LOGS" | wc -l)
          echo "$COUNT"
          echo "::set-env name=COMMIT_NUMBER_OF_DAY::$COUNT"
          echo "::set-env name=COMMIT_DATE::$(TZ=UTC git log --since='0:00' --date=short-local --format=%cd -1)"
        id: commit_timestamp
        if: "!contains(matrix.os, 'windows')"

      - run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - run: ls -lR $GITHUB_WORKSPACE
        if: false

      - uses: k0kubun/action-slack@v2.0.0
        with:
          payload: |
            {
              "attachments": [{
                "text": "${{ job.status }}: ${{ matrix.os }} ${{ env.COMMIT_TIMESTAMP }} ${{ env.COMMIT_DATE }}_${{ env.COMMIT_NUMBER_OF_DAY }} <https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks|${{ github.workflow }}> "
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
