name: ruby-master

on:
  repository_dispatch:
    types:
      - "ruby-master"
  workflow_dispatch:
    inputs:
      RUBY_PATCH_URL:
        description: Patch URL
        required: false
      cppflags:
        description: configure cppflags
        required: false
        default: "-DRUBY_DEBUG -DVM_CHECK_MODE=1 -DRGENGC_CHECK_MODE -DENC_DEBUG -DUSE_RUBY_DEBUG_LOG=1"

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Checkout ruby/ruby
        run: git clone -q --single-branch --depth=1 https://github.com/ruby/ruby ruby
        shell: bash
      - name: Apply patch
        run: |
          set -x
          curl -sSL "${RUBY_PATCH_URL}" -o ruby.patch
          cd ruby/
          git apply ../ruby.patch
        shell: bash
        env:
          RUBY_PATCH_URL: "${{ github.event.inputs.RUBY_PATCH_URL }}"
        if: "${{ github.event.inputs.RUBY_PATCH_URL != '' }}"

      # - name: Install libraries
      #   run: |
      #     brew install openssl@3 readline libyaml gmp rust
      - name: Set ENV
        run: |
          echo "JOBS=-j$((1 + $(sysctl -n hw.activecpu)))" >> $GITHUB_ENV
      - name: configure
        run: >
          cd ruby/ &&
          ./autogen.sh &&
          ./configure
          'cppflags=${{ github.event.inputs.cppflags }}'
          "--with-openssl-dir=$(brew --prefix openssl@3)"
          "--with-readline-dir=$(brew --prefix readline)"
          '--enable-yjit=dev_nodebug'
          '--disable-install-doc'
      - name: make
        run: cd ruby/ && make $JOBS all
      - name: make install
        run: cd ruby/ && make install
      - name: make install-doc
        run: cd ruby/ && make install-doc
      - name: make check
        run: cd ruby/ && make check TESTS="-v -n /test_gc_stress_at_startup/"
