name: Scheduled merge

on:
  schedule:
    - cron: '55 6 * * *'

permissions:
  pull-requests: write
  contents: write

jobs:
  scheduled_merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Merge scheduled PRs
      run: |
        pr_urls=($(gh pr list --label 'Scheduled Merge' --search 'status:success review:approved' --json url --jq 'map(.url)[]'))
        for pr_url in "${pr_urls[@]}"; do
          echo "Merge $pr_url"
          gh pr merge --auto --merge "$pr_url"
        done
