name: Scheduled merge

on:
  schedule:
    - cron: '30,40,50 7 * * *'

permissions:
  pull-requests: write
  contents: write

jobs:
  scheduled_merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Merge scheduled PRs
      run: |
        # search_condition='status:success review:approved'
        search_condition='review:approved'
        pr_urls=($(gh pr list --label scheduled_merge --search "$search_condition" --json url --jq 'map(.url)[]'))
        for pr_url in "${pr_urls[@]}"; do
          echo "Merge $pr_url"
          gh pr merge --auto --merge "$pr_url"
        done
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
