name: snapshot
on: push

jobs:
  check-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev bison- autoconf- ruby- git-
      - name: Download snapshot.tar.xz
        run: wget https://cache.ruby-lang.org/pub/ruby/snapshot.tar.xz
      - name: Extract
        run: tar xf snapshot.tar.xz
      - name: Fixed world writable dirs
        run: |
          chmod go-w $HOME
          sudo chmod -R go-w /usr/share
      - name: Set ENV
        run: |
          echo '##[set-env name=JOBS]'-j$((1 + $(nproc --all)))
      - name: configure
        run: cd snapshot && ./configure
      - name: make
        run: cd snapshot && make $JOBS
      - name: make check
        run: cd snapshot && make -s $JOBS check
        env:
          TESTOPTS: "$JOBS -q --tty=no"
          MSPECOPT: "-ff" # not using `-j` because sometimes `mspec -j` silently dies
