name: snapshot
on: push

jobs:
  check-ci-skip:
    runs-on: ubuntu-latest
    steps:
      - name: Check [ci skip]
        run: echo ng
        if: contains(github.event.head_commit.message, '[ci skip]')

  check-snapshot:
    runs-on: ubuntu-latest
    needs: check-ci-skip
    steps:
      - run: env | sort
      - name: Debug GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Debug job context
        run: echo "$JOB_CONTEXT"
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
      - name: Debug steps context
        run: echo "$STEPS_CONTEXT"
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
