name: snapshot-master

on:
  repository_dispatch:
    types:
      - "make-snapshot"
      - "snapshot-master"
  workflow_dispatch:
    inputs:
      RUBY_PATCH_URL:
        description: Patch URL
        required: false

jobs:
  make-snapshot:
    runs-on: ubuntu-latest
    env:
      archname: snapshot-master
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/make-snapshot
        with:
          ruby-patch-url: ${{ inputs.RUBY_PATCH_URL }}
      - uses: actions/upload-artifact@master
        with:
          name: Packages
          path: pkg
      - uses: actions/upload-artifact@master
        with:
          name: Info
          path: pkg/info
      - name: Check pkg
        run: |
          set -x
          ls -al pkg
          7z x pkg/*.zip $archname/revision.h
          cat $archname/revision.h
          7z l pkg/*.zip $archname/ChangeLog
