name: make-snapshot

on:
  push:
    branches:
      - '*'

jobs:
  check-snapshot-ruby_2_4:
    runs-on: ubuntu-latest
    steps:
      - name: env when ruby/ruby
        run: env
        if: github.repository == 'ruby/ruby'
      - name: env when znz/memo
        run: env
        if: github.repository == 'znz/memo'
