name: test-mix-openssl

on:
  repository_dispatch:
    types: "test-mix-openssl"

# on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - run: |
        if [ -d /github/home -a ! -e /home/runner ]; then
          ln -s /github/home /home/runner
        fi
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
    - uses: ruby/setup-ruby@master
      with:
        ruby-version: 2.3
    - name: Install mysql2 gem
      run: gem install mysql2
    - name: Load libssl.so.1.0.0 and libssl.so.1.1
      run: ruby -r openssl -r mysql2 -e 0
