name: tmate

on:
  repository_dispatch:
    types:
      - tmate-*
  workflow_dispatch:
    inputs:
      os:
        description: runs-on
        required: true

jobs:
  workflow:
    runs-on: "${{ github.event.inputs.os }}"
    if: "${{ github.event.inputs.os != '' }}"
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@e5c7151931ca95bad1c6f4190c730ecf8c7dde48 # v3.19

  ubuntu:
    runs-on: ubuntu-latest
    if: contains(github.event.action, 'ubuntu')
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@e5c7151931ca95bad1c6f4190c730ecf8c7dde48 # v3.19

  macos:
    runs-on: macos-latest
    if: contains(github.event.action, 'macos')
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@e5c7151931ca95bad1c6f4190c730ecf8c7dde48 # v3.19

  windows:
    runs-on: windows-latest
    if: contains(github.event.action, 'windows')
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@e5c7151931ca95bad1c6f4190c730ecf8c7dde48 # v3.19
