name: tmate

on:
  repository_dispatch:
    types:
      - tmate-*

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    if: contains(github.event.action, 'ubuntu')
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@1005f9c9db5f1b055a495e72c6e589764984baf6 # v3.14

  macos:
    runs-on: macos-latest
    if: contains(github.event.action, 'macos')
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@1005f9c9db5f1b055a495e72c6e589764984baf6 # v3.14

  windows:
    runs-on: windows-latest
    if: contains(github.event.action, 'windows')
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@1005f9c9db5f1b055a495e72c6e589764984baf6 # v3.14
