name: tmate

on:
  repository_dispatch:
    types:
      - tmate-*
  workflow_dispatch:
    inputs:
      os:
        description: runs-on
        required: true

jobs:
  workflow:
    runs-on: "${{ github.event.inputs.os }}"
    if: "${{ github.event.inputs.os != '' }}"
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 # v3.23

  ubuntu:
    runs-on: ubuntu-latest
    if: contains(github.event.action, 'ubuntu')
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 # v3.23

  macos:
    runs-on: macos-latest
    if: contains(github.event.action, 'macos')
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 # v3.23

  windows:
    runs-on: windows-latest
    if: contains(github.event.action, 'windows')
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 # v3.23
