name: ruby-windows
on:
  repository_dispatch:
    types:
      - ruby-windows

jobs:
  make:
    strategy:
      matrix:
        test_task: [test]
        os: [windows-2019, windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      GITPULLOPTIONS: --no-tags origin ${{github.ref}}
      PATCH: C:\msys64\usr\bin\patch.exe
    steps:
      - run: md build
        working-directory:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            patch
      - run: |
          dir /b /s *patch.exe
        working-directory: C:\
        shell: cmd
      - run: |
          dir /b /s *patch.exe
        working-directory: D:\
        shell: cmd
