name: ruby-windows
on:
  repository_dispatch:
    types:
      - ruby-windows

jobs:
  make:
    strategy:
      matrix:
        test_task: [test]
        os: [windows-2016, windows-2019]
        vs: [2017, 2019]
        exclude:
          - os: windows-2016
            vs: 2019
          - os: windows-2019
            vs: 2017
      fail-fast: false
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Install libraries with vcpkg
        run: |
          vcpkg --triplet x64-windows install readline zlib
      - name: Install libraries with chocolatey
        run: |
          choco config get cacheLocation
          choco install --no-progress openssl winflexbison3
      - name: Checkout ruby/ruby
        run: |
          git clone --depth=50 https://github.com/ruby/ruby src
      - run: ./src/tool/actions-commit-info.sh
        shell: bash
     - run: sed -i -e 's/echo off/echo on/' ./src/win32/configure.bat
       shell: bash
      - name: Configure
        run: |
          md build
          cd build
          call "C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.vs }}\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set OPENSSL_DIR=C:\Program Files\OpenSSL-Win64
          ../src/win32/configure.bat --disable-install-doc --without-ext=+,dbm,gdbm --enable-bundled-libffi --with-opt-dir=C:/vcpkg/installed/x64-windows "--with-openssl-dir=%OPENSSL_DIR:\=/%"
        shell: cmd
      - name: nmake
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.vs }}\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set YACC=win_bison
          cd build
          nmake up
          nmake
        shell: cmd
      - name: nmake install
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.vs }}\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set YACC=win_bison
          cd build
          nmake DESTDIR=ruby_%COMMIT_DATE%_%COMMIT_NUMBER_OF_DAY% install
        shell: cmd
      - uses: actions/upload-artifact@master
        with:
          name: ruby_vs${{ matrix.vs }}_${{ env.COMMIT_DATE }}_${{ env.COMMIT_NUMBER_OF_DAY }}
          path: src\build\ruby_${{ env.COMMIT_DATE }}_${{ env.COMMIT_NUMBER_OF_DAY }}
      - name: nmake test
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.vs }}\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd build
          nmake ${{ matrix.test_task }}
        shell: cmd
